const fs = require('fs');
const path = require('path');
const { Parser } = require('@dbml/core');

const ROOT = path.resolve(__dirname, '..', '..');
const SCHEMA = path.join(ROOT, 'database', 'schema.dbml');
const OUT = path.join(ROOT, 'docs', 'schema.mmd');
const README = path.join(ROOT, 'README.md');

// B5-05: маркеры секции README, зеркало docs/schema.mmd (README = единый источник отображения)
const MARK_START = '<!-- SCHEMA-MMD-START -->';
const MARK_END = '<!-- SCHEMA-MMD-END -->';

const KEY_PRIORITY = { PK: 0, FK: 1, UK: 2 };

function mermaidType(rawType) {
  return String(rawType).split('(')[0].trim();
}

function fieldNote(field) {
  if (!field.note) return '';
  if (typeof field.note === 'string') return field.note;
  if (typeof field.note.value === 'string') return field.note.value;
  return '';
}

function attributeLine(table, field, fkFields) {
  const keys = [];
  if (field.pk) keys.push('PK');
  if (field.unique) keys.push('UK');
  if (fkFields.has(table.name + '.' + field.name)) keys.push('FK');
  keys.sort((a, b) => KEY_PRIORITY[a] - KEY_PRIORITY[b]);

  const primary = keys.length ? ' ' + keys[0] : '';
  const commentParts = keys.slice(1);
  const note = fieldNote(field).replace(/"/g, "'").replace(/[()]/g, '');
  if (note) commentParts.push(note);
  const comment = commentParts.length ? ' "' + commentParts.join('; ') + '"' : '';

  return '    ' + mermaidType(field.type.type_name) + ' ' + field.name + primary + comment;
}

try {
  const dbml = fs.readFileSync(SCHEMA, 'utf8');
  const model = Parser.parse(dbml, 'dbml').export();

  const fkFields = new Set();
  const relLines = [];

  for (const schema of model.schemas) {
    for (const ref of schema.refs) {
      for (const endpoint of ref.endpoints) {
        if (endpoint.relation === '*') {
          for (const fieldName of endpoint.fieldNames) {
            fkFields.add(endpoint.tableName + '.' + fieldName);
          }
        }
      }
      const parent = ref.endpoints[0];
      const child = ref.endpoints[1];
      if (parent.relation === '1' && child.relation === '*') {
        relLines.push('  ' + parent.tableName + ' ||--o{ ' + child.tableName + ' : ""');
      }
    }
  }

  const entityLines = [];
  for (const schema of model.schemas) {
    for (const table of schema.tables) {
      entityLines.push('  ' + table.name + ' {');
      for (const field of table.fields) {
        entityLines.push(attributeLine(table, field, fkFields));
      }
      entityLines.push('  }');
    }
  }

  const mermaid =
    '%% AUTOGENERATED by tools/dbml/render.cjs from database/schema.dbml. DO NOT EDIT.\n' +
    'erDiagram\n' +
    entityLines.join('\n') + '\n' +
    relLines.join('\n') + '\n';

  fs.writeFileSync(OUT, mermaid);
  console.log('OK: ' + path.relative(ROOT, OUT) + ' generated (pure mermaid, no fence)');

  // B5-05: зеркалируем секцию README между маркерами из свежего docs/schema.mmd.
  let readme = fs.readFileSync(README, 'utf8');
  const startIdx = readme.indexOf(MARK_START);
  const endIdx = startIdx === -1 ? -1 : readme.indexOf(MARK_END, startIdx + MARK_START.length);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    console.error(
      'README.md: не найдены маркеры ' + MARK_START + ' / ' + MARK_END +
      ' — добавьте их вокруг mermaid-фенса (задача B5-05); секция README не синхронизирована.'
    );
    process.exit(1);
  }

  const section = '\n```mermaid\n' + mermaid + '```\n';
  readme = readme.slice(0, startIdx + MARK_START.length) + section + readme.slice(endIdx);
  fs.writeFileSync(README, readme);
  console.log('OK: README.md schema section synced (' + MARK_START + ' … ' + MARK_END + ')');
} catch (err) {
  console.error('DBML -> mermaid error: ' + err.message);
  process.exit(1);
}